apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: project
data:
  # postgres://admin:password@postgres-svc:5432/projectdb
  DATABASE_URL: cG9zdGdyZXM6Ly9hZG1pbjpwYXNzd29yZEBwb3N0Z3Jlcy1zdmM6NTQzMi9wcm9qZWN0ZGIK
