apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/namespace.yaml

  - manifests/configmap.yaml
  - manifests/secrets.example.yaml

  - volumes/persistentvolumeclaim.yaml

  - manifests/service.yaml
  - manifests/statefulset.yaml

  - manifests/deployment.yaml

  - manifests/ingress.yaml

  - manifests/jobs.yaml

# Define images to allow easy updates
images:
  - name: PROJECT/TODO-APP
    newName: emanueletoma/kubernetes
    newTag: todo-app
  - name: PROJECT/TODO-BACKEND
    newName: emanueletoma/kubernetes
    newTag: todo-backend
  - name: PROJECT/WIKICRON
    newName: emanueletoma/kubernetes
    newTag: wikicron
