name: Release Todo Application

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: dwk-images
  DEPLOYMENT: todo-app
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker $REGISTRY

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: 'Form image tags'
        run: |-
          echo "FRONTEND_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-frontend:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          echo "BACKEND_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-backend:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          echo "WIKICRON_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/wikicron:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build Frontend
        run: docker build --tag $FRONTEND_TAG ./todo-app/frontend

      - name: Build Backend
        run: docker build --tag $BACKEND_TAG ./todo-app/backend

      - name: Build Wikicron
        run: docker build --tag $WIKICRON_TAG ./todo-app/wikicron

      - name: Publish Frontend
        run: docker push $FRONTEND_TAG

      - name: Publish Backend
        run: docker push $BACKEND_TAG

      - name: Publish Wikicron
        run: docker push $WIKICRON_TAG

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy
        run: |-
          kubectl create namespace project --dry-run=client -o yaml | kubectl apply -f -
          cd todo-app
          kustomize edit set image PROJECT/TODO-APP=$FRONTEND_TAG
          kustomize edit set image PROJECT/TODO-BACKEND=$BACKEND_TAG
          kustomize edit set image PROJECT/WIKICRON=$WIKICRON_TAG
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT -n project
          kubectl get services -o wide -n project
